# -*- coding: utf-8 -*-
"""Лента событий по-человечески: выкатка на сервер.

Владелец 25.08: «сделай, чтобы человекопонятно было — отбивка, за что
отбивка, письмо отправлено и тд». В ленте стояли коды, а причина лежала в
detail_json, куда панель не смотрела.

ПОЧЕМУ НЕ КАТИМ СВОЙ dist. web/src на сервере разошёлся с песочницей
(styles.css 40575 против 48856) — рядом работает другая сессия. Свой бандл
затёр бы её вёрстку. Поэтому правим СЕРВЕРНЫЕ исходники по якорям и
собираем там же: сборка возьмёт и чужие правки, и мои.

Порядок: .bak каждому файлу, правки, py_compile для питона, npm run build
для фронта. Любой сбой откатывает ВСЁ разом.

    pl_run.py lenta_slovami.py            # вхолостую
    pl_run.py lenta_slovami.py primenit   # применить
"""
import base64
import io
import json
import os
import py_compile
import shutil
import subprocess
import sys
import time

ПАКЕТ = r"C:\sender\sender"
ФРОНТ = os.path.join(ПАКЕТ, "web")
ПРИМЕНИТЬ = "primenit" in sys.argv[1:]

ГРУЗ_B64 = (
    "eyJtb2R1bGUiOiAiSXlBdEtpMGdZMjlrYVc1bk9pQjFkR1l0T0NBdEtpMEtJaUlpMEp2UXRkQzkw"
    "WUxRc0NEUmdkQyswTEhSaTlHQzBMalF1U0RRdjlDK0xkR0gwTFhRdTlDKzBMTFF0ZEdIMExYUmdk"
    "QzYwTGc2SU5HSDBZTFF2aURSZ2RDNzBZUFJoOUM0MEx2UXZ0R0IwWXdnMExnZzBMZlFzQ0RSaDlH"
    "QzBMNHVDZ3JRa2RDcjBKdlFuaTRnMEpJZzBMdlF0ZEM5MFlMUXRTRFJnZEdDMEw3Umo5QzcwTGdn"
    "MExyUXZ0QzAwWXM2SUhObGJuUXNJR0p2ZFc1alpTd2djM1Z3Y0hKbGMzTXNJSEpsY0d4NVgyRjFk"
    "RzhzQ25KbGFtVmpkRjl6Y0dGdExpRFFudEMvMExYUmdOQ3cwWUxRdnRHQUlOQ3kwTGpRdE5DMTBM"
    "c2d3cXRpYjNWdVkyWEN1eURRdUNEUXZkQzFJTkMzMEwzUXNOQzdJTkM5MExnZzBMZlFzQ0RSaDlH"
    "QzBMNGcwTDdSZ3RDeDBMalFzdEM2MExBc0lOQzkwTGdnMExyUXNOQzYwTDdRdk5HREN0Q3cwTFRS"
    "Z05DMTBZSFJneURpZ0pRZzBML1JnTkM0MFlmUXVOQzkwTEFnMEx2UXRkQzIwTERRdTlDd0lOQ3lJ"
    "R1JsZEdGcGJGOXFjMjl1TENEUXV0R0QwTFRRc0NEUXY5Q3cwTDNRdGRDNzBZd2cwTDNRdFNEUmdk"
    "QzgwTDdSZ3RHQTBMWFF1OUN3SU5DeTBMN1FzdEdCMExVdUN0Q1MwTHZRc05DMDBMWFF1OUMxMFlZ"
    "Z01qVXVNRGd1TWpBeU5qb2d3cXZSZ2RDMDBMWFF1OUN3MExrc0lOR0gwWUxRdnRDeDBZc2cwWWZR"
    "dGRDNzBMN1FzdEMxMExyUXZ0Qy8wTDdRdmRHUDBZTFF2ZEMrSU5DeDBZdlF1OUMrSU9LQWxDRFF2"
    "dEdDMExIUXVOQ3kwTHJRc0N3ZzBMZlFzQ0RSaDlHQzBMNEswTDdSZ3RDeDBMalFzdEM2MExBc0lO"
    "Qy8wTGpSZ2RHTTBMelF2aURRdnRHQzBML1JnTkN3MExMUXU5QzEwTDNRdmlEUXVDRFJndEN3MExv"
    "ZzBMVFFzTkM3MExYUXRjSzdMZ29LMEtIUW90Q1EwSnZRbmk0ZzBLTFF1TkMvSU5DLzBMWFJnTkMx"
    "MExMUXZ0QzAwTGpSZ3RHQjBZOGcwWUhRdTlDKzBMTFFzTkM4MExnc0lOQ3dJTkdBMFkvUXROQysw"
    "THdnMExqUXROR1IwWUlnMExyUXZ0R0EwTDdSZ3RDNjBMRFJqeURRdjlHQTBMalJoOUM0MEwzUXND"
    "d2cwWUhRdnRDeDBZRFFzTkM5MEwzUXNOR1BJTkM0MExjSzBZTFF2dEN6MEw0c0lOR0gwWUxRdmlE"
    "UmdOQzEwTERRdTlHTTBMM1F2aURRdTlDMTBMYlF1TkdDSU5DeUlHUmxkR0ZwYkNBbzBMclF1OUdP"
    "MFlmUXVDRFJnZEN5MExYUmdOQzEwTDNSaXlEUXY5QytJTkN4MExEUXQ5QzFJREkxTGpBNExDRFFz"
    "Q0RRdmRDMUN0R0QwTFBRc05DMDBMRFF2ZEdMS1RvZzBZTWcwTDdSZ3RDeDBMalFzdEM2MExnZzRv"
    "Q1VJTkMwMExqUXNOQ3owTDNRdnRHQjBZTFF1TkM2MExBZ1UwMVVVQ0RRdUNEUXNOQzAwWURRdGRH"
    "QkxDRFJneURSZ2RHQzBMN1F2eTNRdTlDNDBZSFJndEN3SU9LQWxDRFF0OUN3SU5HSDBZTFF2Z3JR"
    "c3RDOTBMWFJnZEM3MExnc0lOR0RJTkMvMFlEUXZ0Qy8wWVBSZ2RDNjBMQWc0b0NVSU5DLzBMN1Jo"
    "OUMxMEx6Umd5RFF2ZEMxSU5HQjBMdlFzTkM3MExnc0lOR0RJTkMrMFlMUXN0QzEwWUxRc0NEaWdK"
    "UWcwTHpRdGRHQzBMclFzQ0RSZ05DdzBMZlFzZEMrMFlEUXNDNEtDdENmMEtEUWtOQ1MwSmpRbTlD"
    "ZUlOQ24wSlhRb2RDaTBKM1FudENoMEtMUW1DNGcwSjNRdGRDMzBMM1FzTkM2MEw3UXZOR0wwTGtn"
    "MExyUXZ0QzBJTkNkMEpVZzBML1JnTkdQMFlmUXRkQzhPaURRdjlDKzBMclFzTkMzMFl2UXN0Q3cw"
    "TFhRdkNEUXV0Q3cwTG9nMExYUmdkR0MwWXd1SU5DZjBZUFJnZEdDMExEUmp3clF1dEM3MExYUmd0"
    "QzYwTEFnMEx2Umc5R0gwWWpRdFNEUXN0R0wwTFRSZzlDODBMRFF2ZEM5MEw3UXVTRFF2OUdBMExq"
    "Umg5QzQwTDNSaXl3ZzBMQWcwTExSaTlDMDBZUFF2TkN3MEwzUXZkR0wwTGtnMEwvUXRkR0EwTFhR"
    "c3RDKzBMUWcwWVhSZzlDMjBMVWcwTERRdmRDejBMdlF1TkM1MFlIUXV0QyswTFBRdmk0S0lpSWlD"
    "bVp5YjIwZ1gxOW1kWFIxY21WZlh5QnBiWEJ2Y25RZ1lXNXViM1JoZEdsdmJuTUtDbWx0Y0c5eWRD"
    "QnlaUXBtY205dElIUjVjR2x1WnlCcGJYQnZjblFnUVc1NUxDQlBjSFJwYjI1aGJBb0swSy9Rb05D"
    "YjBLdlFtdENZSUQwZ2V3b2dJQ0FnSW5ObGJuUWlPaUFpMEwvUXVOR0IwWXpRdk5DK0lOQyswWUxR"
    "djlHQTBMRFFzdEM3MExYUXZkQytJaXdLSUNBZ0lDSmtaV3hwZG1WeVpXUWlPaUFpMEwvUXVOR0Iw"
    "WXpRdk5DK0lOQzAwTDdSZ2RHQzBMRFFzdEM3MExYUXZkQytJaXdLSUNBZ0lDSnZjR1Z1SWpvZ0l0"
    "Qy8wTGpSZ2RHTTBMelF2aURRdnRHQzBMclJnTkdMMEx2UXVDSXNDaUFnSUNBaVltOTFibU5sSWpv"
    "Z0l0QyswWUxRc2RDNDBMTFF1dEN3SU9LQWxDRFF2OUM0MFlIUmpOQzgwTDRnMEwzUXRTRFF0TkMr"
    "MFlqUXU5QytJaXdLSUNBZ0lDSnlaV3BsWTNSZmMzQmhiU0k2SUNMUXY5QyswWWZSZ3RDKzBMTFF1"
    "TkM2SU5DOTBMVWcwTC9SZ05DNDBMM1JqOUM3SU5DLzBMalJnZEdNMEx6UXZpSXNDaUFnSUNBaVky"
    "OXRjR3hoYVc1MElqb2dJdEMyMExEUXU5QyswTEhRc0NEUXZkQ3dJTkdCMEwvUXNOQzhJaXdLSUNB"
    "Z0lDSnlaWEJzZVNJNklDTFF2dEdDMExMUXRkR0NJTkM2MEx2UXVOQzEwTDNSZ3RDd0lpd0tJQ0Fn"
    "SUNKeVpYQnNlVjloZFhSdklqb2dJdEN3MExMUmd0QyswTDdSZ3RDeTBMWFJnaURRdXRDNzBMalF0"
    "ZEM5MFlMUXNDSXNDaUFnSUNBaWNtVndiSGxmYzJWdWRDSTZJQ0xRdk5HTElOQyswWUxRc3RDMTBZ"
    "TFF1TkM3MExnaUxBb2dJQ0FnSW5OMWNIQnlaWE56SWpvZ0l0Q3cwTFRSZ05DMTBZRWcwTElnMFlI"
    "Umd0QyswTDh0MEx2UXVOR0IwWUxRdFNJc0NpQWdJQ0FpZFc1emRXSnpZM0pwWW1VaU9pQWkwTDdS"
    "Z3RDLzBMalJnZEM2MExBaUxBb2dJQ0FnSW5OcmFYQWlPaUFpMEwvUXVOR0IwWXpRdk5DK0lOQy8w"
    "WURRdnRDLzBZUFJpZEMxMEwzUXZpSXNDaUFnSUNBaWNtVjBjbmxmYzJOb1pXUjFiR1ZrSWpvZ0l0"
    "QzkwTERRdDlDOTBMRFJoOUMxMEwwZzBML1F2dEN5MFlMUXZ0R0FJaXdLSUNBZ0lDSmthWFpwYzJs"
    "dmJsOW5ZWFJsWDJKc2IyTnJJam9nSXRDMzBMRFJnZEM3MEw3UXZTRFF2ZEN3MEwvUmdOQ3cwTExR"
    "dTlDMTBMM1F1TkdQSWl3S0lDQWdJQ0p2ZEdobGNpSTZJQ0xRc3RHRjBMN1F0TkdQMFluUXRkQzFJ"
    "TkN5MEwzUXRTRFF2OUMxMFlEUXRkQy8wTGpSZ2RDNjBMZ2lMQXA5Q2dvaklOQ1UwTGpRc05DejBM"
    "M1F2dEdCMFlMUXVOQzYwTEFnVTAxVVVDRFJnZEM3MEw3UXN0Q3cwTHpRdUM0ZzBKL1F2dEdBMFkv"
    "UXROQyswTG9nMExMUXNOQzIwTFhRdlRvZzBZSFF2ZEN3MFlmUXNOQzcwTEFnMFlMUXZ0R0gwTDNS"
    "aTlDMUlOQy8wWURRdU5DMzBMM1FzTkM2MExnc0lOQy8wTDdSZ3RDKzBMd0tJeURRdnRDeDBZblF1"
    "TkMxSU9LQWxDRENxMjFoYVd4aWIzZ2dkVzVoZG1GcGJHRmliR1hDdXlEUXNkR0wwTExRc05DMTBZ"
    "SWcwTGdnMFlNZzBML1F0ZEdBMExYUXY5QyswTHZRdmRDMTBMM1F2ZEMrMExQUXZpRFJqOUdKMExq"
    "UXV0Q3dMZ3BmMEo3UW90Q1IwSmpRa3RDYTBKZ2dQU0FvQ2lBZ0lDQW9jaUp1YnlCemRXTm9JSFZ6"
    "WlhKOGFXNTJZV3hwWkNCdFlXbHNZbTk0ZkhWelpYSWdkVzVyYm05M2JueDFibXR1YjNkdUlIVnpa"
    "WEo4SWdvZ0lDQWdJSElpMExEUXROR0EwTFhSZ2RDdzBZSWcwTDNRdFNEUXZkQ3cwTG5RdE5DMTBM"
    "MThOVnd1TVZ3dU1TSXNJQ0xSZ3RDdzBMclF2dEN6MEw0ZzBZL1JpZEM0MExyUXNDRFF2ZEMxMFlJ"
    "aUtTd0tJQ0FnSUNoeUltMWhhV3hpYjNnZ1puVnNiSHh4ZFc5MFlTQmxlR05sWldSbFpIeHZkbVZ5"
    "SUhGMWIzUmhmTkMvMExYUmdOQzEwTC9RdnRDNzBMMGlMQ0FpMFkvUmlkQzQwTG9nMEwvUXRkR0Ew"
    "TFhRdjlDKzBMdlF2ZEMxMEwwaUtTd0tJQ0FnSUNoeUluTndZVzE4TlZ3dU4xd3VNWHhpYkdGamEy"
    "eHBjM1I4WW14dlkydGxaQ0lzSUNMUXY5QyswTHZSZzlHSDBMRFJndEMxMEx2UmpDRFF2OUdBMExq"
    "UXZkR1AwTHNnMExmUXNDRFJnZEMvMExEUXZDSXBMQW9nSUNBZ0tISWlaRzl0WVdsdUlHNXZkQ0Jt"
    "YjNWdVpIeDFibkp2ZFhSbFlXSnNaWHh1YnlCdGVIdzFYQzQwWEM0MGZHaHZjM1FnYm05MElHWnZk"
    "VzVrSWl3S0lDQWdJQ0FpMExUUXZ0QzgwTFhRdlNEUXZkQzFJTkMvMFlEUXVOQzkwTGpRdk5DdzBM"
    "WFJnaURRdjlDKzBZZlJndEdESWlrc0NpQWdJQ0FvY2lKbmNtVjViR2x6ZEh3MFhDNDNYQzR4ZkhS"
    "eWVTQmhaMkZwYmlCc1lYUmxjbncwWEM0eVhDNHdJaXdnSXRHQjBMWFJnTkN5MExYUmdDRFF2OUdB"
    "MEw3UmdkQzQwWUlnMEwvUXZ0Q3kwWUxRdnRHQTBMalJndEdNSU5DLzBMN1F0OUMyMExVaUtTd0tJ"
    "Q0FnSUNoeUluQnZiR2xqZVh6UXQ5Q3cwTC9SZ05DMTBZbDhibTkwSUdGc2JHOTNaV1I4Y21WbWRY"
    "TmxaQ0lzSUNMUXQ5Q3cwTC9SZ05DMTBZSWcwTC9RdnRDNzBMalJndEM0MExyUXZ0QzVJTkMvMEw3"
    "UXU5R0QwWWZRc05HQzBMWFF1OUdQSWlrc0NpQWdJQ0FvY2lKa2FYTmhZbXhsWkh4cGJtRmpkR2wy"
    "Wlh6UXZ0R0MwTHJRdTlHTzBZY2lMQ0FpMFkvUmlkQzQwTG9nMEw3Umd0QzYwTHZSanRHSDBaSFF2"
    "U0lwTEFvcENncGYwS0hRb3RDZTBKOWYwSnZRbU5DaDBLSWdQU0I3Q2lBZ0lDQWlZbTkxYm1ObFgy"
    "aGhjbVFpT2lBaTBMYlJrZEdCMFlMUXV0Q3cwWThnMEw3Umd0Q3gwTGpRc3RDNjBMQWlMQW9nSUNB"
    "Z0ltSnZkVzVqWlNJNklDTFF2dEdDMExIUXVOQ3kwTHJRc0NJc0NpQWdJQ0FpWTI5dGNHeGhhVzUw"
    "SWpvZ0l0QzIwTERRdTlDKzBMSFFzQ0RRdmRDd0lOR0IwTC9Rc05DOElpd0tJQ0FnSUNKMWJuTjFZ"
    "bk5qY21saVpTSTZJQ0xRdnRHQzBML1F1TkdCMExEUXU5R0IwWThpTEFvZ0lDQWdJbTFoYm5WaGJD"
    "STZJQ0xRc3RDOTBMWFJnZEdSMEwwZzBMTFJnTkdEMFlmUXZkR0QwWTRpTEFvZ0lDQWdJbVJsWVd4"
    "ZmFXNWZjSEp2WjNKbGMzTWlPaUFpMFlIUXROQzEwTHZRdXRDd0lOR0QwTGJRdFNEUXNpRFJnTkN3"
    "MExIUXZ0R0MwTFVpTEFwOUNncGYwSi9Rb05DZTBKL1FvOUNoMEpvZ1BTQjdDaUFnSUNBaWNtVndi"
    "R2xsWkNJNklDTFF1dEM3MExqUXRkQzkwWUlnMFlQUXR0QzFJTkMrMFlMUXN0QzEwWUxRdU5DN0lp"
    "d0tJQ0FnSUNKemRYQndjbVZ6YzJWa0lqb2dJdEN3MExUUmdOQzEwWUVnMExJZzBZSFJndEMrMEw4"
    "dDBMdlF1TkdCMFlMUXRTSXNDaUFnSUNBaVpIVndiR2xqWVhSbElqb2dJdEdDMExEUXV0QyswTHpS"
    "Z3lEUmc5QzIwTFVnMEwvUXVOR0IwTERRdTlDNElpd0tJQ0FnSUNKdWIxOWtZWFJoSWpvZ0l0Qzkw"
    "TFVnMFlYUXN0Q3cwWUxRdU5DNzBMNGcwTFRRc05DOTBMM1JpOUdGSU5DMDBMdlJqeURRdjlDNDBZ"
    "SFJqTkM4MExBaUxBb2dJQ0FnSW1kaGRHVWlPaUFpMEwzUXRTRFF2OUdEMFlIUmd0QzQwTHNnMExQ"
    "UXRkQzUwWUlnMFlEUXRkQy8wWVBSZ3RDdzBZYlF1TkM0SWl3S2ZRb0tYOUNmMEo3UWt0Q2kwSjdR"
    "b0NBOUlIc0tJQ0FnSUNKemIyWjBYMkp2ZFc1alpTSTZJQ0xRdk5HUDBMUFF1dEN3MFk4ZzBMN1Jn"
    "dEN4MExqUXN0QzYwTEFpTEFvZ0lDQWdJblJ5WVc1emFXVnVkQ0k2SUNMUXN0R0EwTFhRdk5DMTBM"
    "M1F2ZEdMMExrZzBZSFFzZEMrMExrZzBML1F2dEdIMFlMUXZ0Q3kwTGpRdXRDd0lpd0tmUW9LQ21S"
    "bFppQjVZWEpzZVdzb1pYWmxiblJmZEhsd1pUb2djM1J5S1NBdFBpQnpkSEk2Q2lBZ0lDQWlJaUxR"
    "b3RDNDBMOGcwWUhRdnRDeDBZdlJndEM0MFk4ZzBZSFF1OUMrMExMUXNOQzgwTGd1SU5DZDBMWFF0"
    "OUM5MExEUXV0QyswTHpSaTlDNUlOQzYwTDdRdENEUXN0QyswTGZRc3RHQTBMRFJpZEN3MExYUXZD"
    "RFF1dEN3MExvZzBMWFJnZEdDMFl3dUlpSWlDaUFnSUNCeVpYUjFjbTRnMEsvUW9OQ2IwS3ZRbXRD"
    "WUxtZGxkQ2h6ZEhJb1pYWmxiblJmZEhsd1pTQnZjaUFpSWlrdWMzUnlhWEFvS1N3Z2MzUnlLR1Yy"
    "Wlc1MFgzUjVjR1VnYjNJZ0lpSXBLUW9LQ21SbFppQmZjR1Z5ZG1GNVlWOXpkSEp2YTJFbzBZTFF0"
    "ZEM2MFlIUmdqb2dRVzU1TENEUXY5R0EwTFhRdE5DMTBMczZJR2x1ZENBOUlEa3dLU0F0UGlCemRI"
    "STZDaUFnSUNEUmdpQTlJQ0lnSWk1cWIybHVLSE4wY2lqUmd0QzEwTHJSZ2RHQ0lHOXlJQ0lpS1M1"
    "emNHeHBkQ2dwS1FvZ0lDQWdjbVYwZFhKdUlOR0NXenJRdjlHQTBMWFF0TkMxMEx0ZENnb0taR1Zt"
    "SUY5a2FXRm5ibTk2S05HQzBMWFF1dEdCMFlJNklITjBjaWtnTFQ0Z2MzUnlPZ29nSUNBZ0lpSWkw"
    "S0hSZ3RHQTBMN1F1dEdESUZOTlZGQXQwTFRRdU5DdzBMUFF2ZEMrMFlIUmd0QzQwTHJRdUNEaWdK"
    "UWcwTElnMExyUXZ0R0EwTDdSZ3RDNjBZUFJqaURRdjlHQTBMalJoOUM0MEwzUmd5RFJnZEM3MEw3"
    "UXN0Q3cwTHpRdUM0aUlpSUtJQ0FnSU5HQ0lEMGdjM1J5S05HQzBMWFF1dEdCMFlJZ2IzSWdJaUlw"
    "Q2lBZ0lDQm1iM0lnMEw3UXNkR0EwTERRdDlDMTBZWXNJTkdCMEx2UXZ0Q3kwTERRdk5DNElHbHVJ"
    "Ri9RbnRDaTBKSFFtTkNTMEpyUW1Eb0tJQ0FnSUNBZ0lDQnBaaUJ5WlM1elpXRnlZMmdvMEw3UXNk"
    "R0EwTERRdDlDMTBZWXNJTkdDTENCeVpTNUpLVG9LSUNBZ0lDQWdJQ0FnSUNBZ2NtVjBkWEp1SU5H"
    "QjBMdlF2dEN5MExEUXZOQzRDaUFnSUNCeVpYUjFjbTRnSWlJS0NncGtaV1lnY0c5amFHVnRkU2hs"
    "ZG1WdWRGOTBlWEJsT2lCemRISXNJR1JsZEdGcGJEb2dUM0IwYVc5dVlXeGJaR2xqZEYwcElDMCtJ"
    "SE4wY2pvS0lDQWdJQ0lpSXRDYTBMN1JnTkMrMFlMUXV0Q3cwWThnMEwvUmdOQzQwWWZRdU5DOTBM"
    "QWcwWUhRdnRDeDBZdlJndEM0MFk4dUlOQ2YwWVBSZ2RHQzBMNGc0b0NVSU5DMzBMM1FzTkdIMExq"
    "UmdpRFF2OUdBMExqUmg5QzQwTDNSaXlEUXVDRFF2ZEMxMFlJZ0tOQyswTEhSaTlHSDBMM1FzTkdQ"
    "SU5DKzBZTFF2OUdBMExEUXN0QzYwTEFwTGlJaUlnb2dJQ0FnWkNBOUlHUmxkR0ZwYkNCcFppQnBj"
    "Mmx1YzNSaGJtTmxLR1JsZEdGcGJDd2daR2xqZENrZ1pXeHpaU0I3ZlFvZ0lDQWcwWUlnUFNCemRI"
    "SW9aWFpsYm5SZmRIbHdaU0J2Y2lBaUlpa0tDaUFnSUNCcFppRFJnaUE5UFNBaVltOTFibU5sSWpv"
    "S0lDQWdJQ0FnSUNCa2MyNGdQU0JrTG1kbGRDZ2laSE51SWlrZ2FXWWdhWE5wYm5OMFlXNWpaU2hr"
    "TG1kbGRDZ2laSE51SWlrc0lHUnBZM1FwSUdWc2MyVWdlMzBLSUNBZ0lDQWdJQ0RRdE5DNDBMRFFz"
    "eUE5SUhOMGNpaGtjMjR1WjJWMEtDSmthV0ZuYm05emRHbGpJaWtnYjNJZ0lpSXBDaUFnSUNBZ0lD"
    "QWcwTHJSZzlDMDBMQWdQU0FpSWdvZ0lDQWdJQ0FnSU5HQjBMSFF2dEM1SUQwZ1pITnVMbWRsZENn"
    "aVptRnBiR1ZrSWlrS0lDQWdJQ0FnSUNCcFppQnBjMmx1YzNSaGJtTmxLTkdCMExIUXZ0QzVMQ0Fv"
    "YkdsemRDd2dkSFZ3YkdVcEtTQmhibVFnMFlIUXNkQyswTGs2Q2lBZ0lDQWdJQ0FnSUNBZ0lOQzYw"
    "WVBRdE5Dd0lEMGdjM1J5S05HQjBMSFF2dEM1V3pCZEtRb2dJQ0FnSUNBZ0lOR0IwTHZRdnRDeTBM"
    "RFF2TkM0SUQwZ1gyUnBZV2R1YjNvbzBMVFF1TkN3MExNcElHOXlJRjl3WlhKMllYbGhYM04wY205"
    "cllTZ0tJQ0FnSUNBZ0lDQWdJQ0FnY21VdWMzVmlLSElpWG5OdGRIQTdYSE1xSWl3Z0lpSXNJTkMw"
    "MExqUXNOQ3pLU3dnTnpBcENpQWdJQ0FnSUNBZ2FXWWcwTHJSZzlDMDBMQWdZVzVrSU5HQjBMdlF2"
    "dEN5MExEUXZOQzRPZ29nSUNBZ0lDQWdJQ0FnSUNCeVpYUjFjbTRnSWlWek9pQWxjeUlnSlNBbzBM"
    "clJnOUMwMExBc0lOR0IwTHZRdnRDeTBMRFF2TkM0S1FvZ0lDQWdJQ0FnSUhKbGRIVnliaURSZ2RD"
    "NzBMN1FzdEN3MEx6UXVDQnZjaURRdXRHRDBMVFFzQ0J2Y2lCZmMyNXBjSEJsZEY5emRISnZhMkVv"
    "WkNrS0NpQWdJQ0JwWmlEUmdpQTlQU0FpY21WcVpXTjBYM053WVcwaU9nb2dJQ0FnSUNBZ0lOQysw"
    "WWpRdU5DeDBMclFzQ0E5SUhOMGNpaGtMbWRsZENnaVpYSnliM0lpS1NCdmNpQWlJaWtLSUNBZ0lD"
    "QWdJQ0RRdXRHQzBMNGdQU0FpMEsvUXZkQzAwTFhRdXRHQklpQnBaaUFpZVdFdVkyTWlJR2x1SU5D"
    "KzBZalF1TkN4MExyUXNDQnZjaUFpZVdGdVpHVjRJaUJwYmlEUXZ0R0kwTGpRc2RDNjBMQXViRzkz"
    "WlhJb0tTQmxiSE5sSUNMUXY5QyswWWZSZ3RDKzBMTFF1TkM2SWdvZ0lDQWdJQ0FnSUhKbGRIVnli"
    "aUFpSlhNZzBMM1F0U0RRdjlHQTBMalF2ZEdQMExzZzBML1F1TkdCMFl6UXZOQytPaURRdjlDKzBM"
    "VFF2dEMzMFlEUXRkQzkwTGpRdFNEUXZkQ3dJTkdCMEwvUXNOQzhJaUFsSU5DNjBZTFF2Z29LSUNB"
    "Z0lHbG1JTkdDSUQwOUlDSnpkWEJ3Y21WemN5STZDaUFnSUNBZ0lDQWcwTC9SZ05DNDBZZlF1TkM5"
    "MExBZ1BTQnpkSElvWkM1blpYUW9JbkpsWVhOdmJpSXBJRzl5SUNJaUtRb2dJQ0FnSUNBZ0lOQ3cw"
    "TFRSZ05DMTBZSFFzQ0E5SUdRdVoyVjBLQ0poWkdSeVpYTnpaWE1pS1FvZ0lDQWdJQ0FnSU5DdzBM"
    "VFJnTkMxMFlFZ1BTQnpkSElvMExEUXROR0EwTFhSZ2RDd1d6QmRLU0JwWmlCcGMybHVjM1JoYm1O"
    "bEtOQ3cwTFRSZ05DMTBZSFFzQ3dnS0d4cGMzUXNJSFIxY0d4bEtTa2dZVzVrSU5DdzBMVFJnTkMx"
    "MFlIUXNDQmxiSE5sSUNJaUNpQWdJQ0FnSUNBZzBZSFF1OUMrMExMUXNOQzgwTGdnUFNCZjBLSFFv"
    "dENlMEo5ZjBKdlFtTkNoMEtJdVoyVjBLTkMvMFlEUXVOR0gwTGpRdmRDd0xDRFF2OUdBMExqUmg5"
    "QzQwTDNRc0NrS0lDQWdJQ0FnSUNCeVpYUjFjbTRnS0NJbGN6b2dKWE1pSUNVZ0tOQ3cwTFRSZ05D"
    "MTBZRXNJTkdCMEx2UXZ0Q3kwTERRdk5DNEtTa3VjM1J5YVhBb0lqb2dJaWtnYVdZZzBMRFF0TkdB"
    "MExYUmdTQmxiSE5sSU5HQjBMdlF2dEN5MExEUXZOQzRDZ29nSUNBZ2FXWWcwWUlnUFQwZ0luTnJh"
    "WEFpT2dvZ0lDQWdJQ0FnSU5DLzBZRFF1TkdIMExqUXZkQ3dJRDBnYzNSeUtHUXVaMlYwS0NKeVpX"
    "RnpiMjRpS1NCdmNpQWlJaWtLSUNBZ0lDQWdJQ0J5WlhSMWNtNGdYOUNmMEtEUW50Q2YwS1BRb2RD"
    "YUxtZGxkQ2pRdjlHQTBMalJoOUM0MEwzUXNDd2cwTC9SZ05DNDBZZlF1TkM5MExBcENnb2dJQ0Fn"
    "YVdZZzBZSWdQVDBnSW5KbGRISjVYM05qYUdWa2RXeGxaQ0k2Q2lBZ0lDQWdJQ0FnMEwvUmdOQzQw"
    "WWZRdU5DOTBMQWdQU0JmMEovUW50Q1MwS0xRbnRDZ0xtZGxkQ2h6ZEhJb1pDNW5aWFFvSW5KbFlY"
    "TnZiaUlwSUc5eUlDSWlLU3dnYzNSeUtHUXVaMlYwS0NKeVpXRnpiMjRpS1NCdmNpQWlJaWtwQ2lB"
    "Z0lDQWdJQ0FnMExQUXU5R0QwTEhRdU5DOTBMQWdQU0JrTG1kbGRDZ2laR1Z3ZEdnaUtRb2dJQ0Fn"
    "SUNBZ0lISmxkSFZ5YmlBb0lpVnpMQ0RRdjlDKzBML1JpOUdDMExyUXNDQWxjeUlnSlNBbzBML1Jn"
    "TkM0MFlmUXVOQzkwTEFzSU5DejBMdlJnOUN4MExqUXZkQ3dLU2tnYVdZZzBMUFF1OUdEMExIUXVO"
    "QzkwTEFnWld4elpTRFF2OUdBMExqUmg5QzQwTDNRc0FvS0lDQWdJR2xtSU5HQ0lHbHVJQ2dpY21W"
    "d2JIa2lMQ0FpY21Wd2JIbGZZWFYwYnlJc0lDSmpiMjF3YkdGcGJuUWlMQ0FpYjNSb1pYSWlLVG9L"
    "SUNBZ0lDQWdJQ0RRdk5DMTBZTFF1dEN3SUQwZ2MzUnlLR1F1WjJWMEtDSnlaWEJzZVY5cmFXNWtJ"
    "aWtnYjNJZ0lpSXBDaUFnSUNBZ0lDQWcwWUxRdGRDNjBZSFJnaUE5SUY5d1pYSjJZWGxoWDNOMGNt"
    "OXJZU2hrTG1kbGRDZ2ljMjVwY0hCbGRDSXBMQ0E0TUNrS0lDQWdJQ0FnSUNCcFppRFF2TkMxMFlM"
    "UXV0Q3dJR0Z1WkNEUmd0QzEwTHJSZ2RHQ09nb2dJQ0FnSUNBZ0lDQWdJQ0J5WlhSMWNtNGdJaVZ6"
    "SU9LQWxDQWxjeUlnSlNBbzBMelF0ZEdDMExyUXNDd2cwWUxRdGRDNjBZSFJnaWtLSUNBZ0lDQWdJ"
    "Q0J5WlhSMWNtNGcwTHpRdGRHQzBMclFzQ0J2Y2lEUmd0QzEwTHJSZ2RHQ0Nnb2dJQ0FnYVdZZzBZ"
    "SWdQVDBnSW5KbGNHeDVYM05sYm5RaU9nb2dJQ0FnSUNBZ0lOQzYwTERRdWlBOUlDTFF2ZEN3MEwv"
    "UXVOR0IwTERRdlNEUmdOR0QwTHJRc05DODBMZ2cwTGpRdHlEUXN0QzEwTEV0MEwvUXZ0R0gwWUxS"
    "aXlJZ2FXWWdaQzVuWlhRb0luSjFZMmh1YjNraUtTQmxiSE5sSUNMUXZ0R0MwTC9SZ05DdzBMTFF1"
    "OUMxMEwwZzBMalF0eURRdjlDdzBMM1F0ZEM3MExnaUNpQWdJQ0FnSUNBZzBZTFF0ZEM4MExBZ1BT"
    "QmZjR1Z5ZG1GNVlWOXpkSEp2YTJFb1pDNW5aWFFvSW5SbGJXRWlLU3dnTmpBcENpQWdJQ0FnSUNB"
    "Z2NtVjBkWEp1SUNnaUpYTTZJQ1Z6SWlBbElDalF1dEN3MExvc0lOR0MwTFhRdk5Dd0tTa2dhV1ln"
    "MFlMUXRkQzgwTEFnWld4elpTRFF1dEN3MExvS0NpQWdJQ0J5WlhSMWNtNGdYM0JsY25aaGVXRmZj"
    "M1J5YjJ0aEtHUXVaMlYwS0NKeVpXRnpiMjRpS1NCdmNpQmtMbWRsZENnaVpYSnliM0lpS1NCdmNp"
    "QWlJaXdnT0RBcENnb0taR1ZtSUY5emJtbHdjR1YwWDNOMGNtOXJZU2hrT2lCa2FXTjBLU0F0UGlC"
    "emRISTZDaUFnSUNCeVpYUjFjbTRnWDNCbGNuWmhlV0ZmYzNSeWIydGhLR1F1WjJWMEtDSnpibWx3"
    "Y0dWMElpa3NJRGN3S1FvPSIsICJweSI6IFt7ImZpbGUiOiAiYXBpL2FwcC5weSIsICJhIjogIlpH"
    "Vm1JRjlsZG1WdWRGOXFjMjl1S0dVcE9nb2dJQ0FnY21WMGRYSnVJSHNpYVdRaU9pQmxMbWxrTENB"
    "aVpYWmxiblJmZEhsd1pTSTZJR1V1WlhabGJuUmZkSGx3WlN3Z0ltTmhiWEJoYVdkdVgybGtJam9n"
    "WlM1allXMXdZV2xuYmw5cFpDd0tJQ0FnSUNBZ0lDQWdJQ0FnSW5CeWIzWnBaR1Z5SWpvZ1pTNXdj"
    "bTkyYVdSbGNpd2dJbTFoYVd4aWIzaGZhV1FpT2lCbExtMWhhV3hpYjNoZmFXUXNDaUFnSUNBZ0lD"
    "QWdJQ0FnSUNKbGRtVnVkRjkwY3lJNklGOXBjMjhvWlM1bGRtVnVkRjkwY3lsOSIsICJyIjogIlpH"
    "Vm1JRjlsZG1WdWRGOXFjMjl1S0dVc0lITjBiM0psUFU1dmJtVXBPZ29nSUNBZ0lpSWkwS0hRdnRD"
    "eDBZdlJndEM0MExVZzBMVFF1OUdQSU5DNzBMWFF2ZEdDMFlzNklOQzYwTDdRdEN3ZzBMQWcwWURS"
    "ajlDMDBMN1F2Q0RSZ3RDK0lOQzIwTFVnMFlIUXNOQzgwTDdRdFNEUmdkQzcwTDdRc3RDdzBMelF1"
    "QzRLQ2lBZ0lDRFFrdEM3MExEUXROQzEwTHZRdGRHR0lESTFMakE0T2lEQ3E5R0IwTFRRdGRDNzBM"
    "RFF1U3dnMFlmUmd0QyswTEhSaXlEUmg5QzEwTHZRdnRDeTBMWFF1dEMrMEwvUXZ0QzkwWS9SZ3RD"
    "OTBMNGcwTEhSaTlDNzBMNGc0b0NVSU5DKzBZTFFzZEM0MExMUXV0Q3dMQ0RRdDlDd0lOR0gwWUxR"
    "dmdvZ0lDQWcwTDdSZ3RDeDBMalFzdEM2MExBc0lOQy8wTGpSZ2RHTTBMelF2aURRdnRHQzBML1Jn"
    "TkN3MExMUXU5QzEwTDNRdnNLN0xpRFFtdEMrMExRZzBMN1JnZEdDMExEUXN0QzcwWS9RdGRDOE9p"
    "RFF2OUMrSU5DOTBMWFF2TkdESU5HQTBMRFFzZEMrMFlMUXNOR08wWUlnMFlUUXVOQzcwWXpSZ3RH"
    "QUlOQzRDaUFnSUNEUmdkR0MwTERSZ05HTDBMVWcwWUhSZ2RHTDBMdlF1dEM0TENEUXNDRENxOUdI"
    "MFlMUXZzSzdJTkM0SU1LcjBML1F2dEdIMExYUXZOR0R3cnNnMFlmUXVOR0MwTERRdGRHQ0lOR0gw"
    "TFhRdTlDKzBMTFF0ZEM2TGlEUW45QyswTHZSZzlHSDBMRFJndEMxMEx2Ump5RFF0TkMrMFlIUmd0"
    "Q3cwWkhRdkFvZ0lDQWcwTGpRdHlEUmdkR0MwTDdSZ05Dd0xDRFF0ZEdCMEx2UXVDRFF2dEM5SU5D"
    "LzBMWFJnTkMxMExUUXNOQzlPaURRc2lEUmdkQ3cwTHpRdnRDOElOR0IwTDdRc2RHTDBZTFF1TkM0"
    "SU5DNzBMWFF0dEM0MFlJZzBZTFF2dEM3MFl6UXV0QytJTkMxMExQUXZpRFF2ZEMrMEx6UXRkR0FM"
    "Z29nSUNBZ0lpSWlDaUFnSUNEUXV0QyswTHpSZ3lBOUlOQzYwTDdRdk5DLzBMRFF2ZEM0MFk4Z1BT"
    "Qk9iMjVsQ2lBZ0lDQnBaaUJ6ZEc5eVpTQnBjeUJ1YjNRZ1RtOXVaU0JoYm1RZ1oyVjBZWFIwY2lo"
    "bExDQWljbVZqYVhCcFpXNTBYMmxrSWl3Z1RtOXVaU2s2Q2lBZ0lDQWdJQ0FnZEhKNU9nb2dJQ0Fn"
    "SUNBZ0lDQWdJQ0RSZ05DMTBMb2dQU0J6ZEc5eVpTNW5aWFJmY21WamFYQnBaVzUwS0dsdWRDaGxM"
    "bkpsWTJsd2FXVnVkRjlwWkNrcENpQWdJQ0FnSUNBZ1pYaGpaWEIwSUVWNFkyVndkR2x2YmpvZ0lD"
    "TWdibTl4WVRvZ1FreEZNREF4SUMwZzBMdlF0ZEM5MFlMUXNDRFF2ZEMxSU5HQjBMelF0ZEMxMFlJ"
    "ZzBML1FzTkMwMExEUmd0R01JTkM0MExjdDBMZlFzQ0RSZ2RHQzBZRFF2dEM2MExnS0lDQWdJQ0Fn"
    "SUNBZ0lDQWcwWURRdGRDNklEMGdUbTl1WlFvZ0lDQWdJQ0FnSUdsbUlOR0EwTFhRdWlCcGN5QnVi"
    "M1FnVG05dVpUb0tJQ0FnSUNBZ0lDQWdJQ0FnMExyUXZ0QzgwWU1nUFNCblpYUmhkSFJ5S05HQTBM"
    "WFF1aXdnSW1WdFlXbHNJaXdnVG05dVpTa0tJQ0FnSUNBZ0lDQWdJQ0FnMExyUXZ0QzgwTC9Rc05D"
    "OTBMalJqeUE5SUdkbGRHRjBkSElvMFlEUXRkQzZMQ0FpWTI5dGNHRnVlVjl1WVcxbElpd2dUbTl1"
    "WlNrS0lDQWdJSEpsZEhWeWJpQjdJbWxrSWpvZ1pTNXBaQ3dnSW1WMlpXNTBYM1I1Y0dVaU9pQmxM"
    "bVYyWlc1MFgzUjVjR1VzSUNKallXMXdZV2xuYmw5cFpDSTZJR1V1WTJGdGNHRnBaMjVmYVdRc0Np"
    "QWdJQ0FnSUNBZ0lDQWdJQ0p3Y205MmFXUmxjaUk2SUdVdWNISnZkbWxrWlhJc0lDSnRZV2xzWW05"
    "NFgybGtJam9nWlM1dFlXbHNZbTk0WDJsa0xBb2dJQ0FnSUNBZ0lDQWdJQ0FpWlhabGJuUmZkSE1p"
    "T2lCZmFYTnZLR1V1WlhabGJuUmZkSE1wTEFvZ0lDQWdJQ0FnSUNBZ0lDQWlZMmgwYnlJNklIbGhj"
    "bXg1YTE5emIySjVkR2w1WVNobExtVjJaVzUwWDNSNWNHVXBMQW9nSUNBZ0lDQWdJQ0FnSUNBaWNH"
    "OWphR1Z0ZFNJNklIQnZZMmhsYlhWZmMyOWllWFJwZVdFb1pTNWxkbVZ1ZEY5MGVYQmxMQ0JuWlhS"
    "aGRIUnlLR1VzSUNKa1pYUmhhV3dpTENCT2IyNWxLU2tzQ2lBZ0lDQWdJQ0FnSUNBZ0lDSnJiMjEx"
    "SWpvZzBMclF2dEM4MFlNc0lDSnJiMjF3WVc1cGVXRWlPaURRdXRDKzBMelF2OUN3MEwzUXVOR1Bm"
    "UT09In0sIHsiZmlsZSI6ICJhcGkvYXBwLnB5IiwgImEiOiAiSUNBZ0lDQWdJQ0J5WlhSMWNtNGdl"
    "eUpsZG1WdWRITWlPaUJiWDJWMlpXNTBYMnB6YjI0b1pTa2dabTl5SUdVZ2FXNGdjbTkzYzExOSIs"
    "ICJyIjogIklDQWdJQ0FnSUNCeVpYUjFjbTRnZXlKbGRtVnVkSE1pT2lCYlgyVjJaVzUwWDJwemIy"
    "NG9aU3dnWkdWd2N5NXpkRzl5WlNrZ1ptOXlJR1VnYVc0Z2NtOTNjMTE5In0sIHsiZmlsZSI6ICJh"
    "cGkvYXBwLnB5IiwgImEiOiAiWm5KdmJTQnpaVzVrWlhJdWQybHlhVzVuSUdsdGNHOXlkQ0JFWlhC"
    "ekxDQmlkV2xzWkY5a1pYQnpJQ0FqSUc1dmNXRTZJRVkwTURFPSIsICJyIjogIlpuSnZiU0J6Wlc1"
    "a1pYSXVkMmx5YVc1bklHbHRjRzl5ZENCRVpYQnpMQ0JpZFdsc1pGOWtaWEJ6SUNBaklHNXZjV0U2"
    "SUVZME1ERUtabkp2YlNCelpXNWtaWEl1YzI5aWVYUnBlV0ZmYzJ4dmRtRnRhU0JwYlhCdmNuUWdj"
    "RzlqYUdWdGRTQmhjeUJ3YjJOb1pXMTFYM052WW5sMGFYbGhDbVp5YjIwZ2MyVnVaR1Z5TG5Odllu"
    "bDBhWGxoWDNOc2IzWmhiV2tnYVcxd2IzSjBJSGxoY214NWF5QmhjeUI1WVhKc2VXdGZjMjlpZVhS"
    "cGVXRT0ifV0sICJ3ZWIiOiBbeyJmaWxlIjogInNyYy9jb21wb25lbnRzL3VpLnRzeCIsICJhIjog"
    "IlpYaHdiM0owSUdaMWJtTjBhVzl1SUZOMFlYUjFjMEpoWkdkbEtIc2djM1JoZEhWekxDQnJhVzVr"
    "SUQwZ0lteGxZV1FpSUgwNklIc2djM1JoZEhWek9pQnpkSEpwYm1jN0lHdHBibVEvT2lBaWJHVmha"
    "Q0lnZkNBaVkyRnRjR0ZwWjI0aUlIMHBJSHNLSUNCamIyNXpkQ0JzWVdKbGJDQTlJR3RwYm1RZ1BU"
    "MDlJQ0pzWldGa0lpQS9JQ2hNUlVGRVgxTlVRVlJWVTF0emRHRjBkWE5kSUh4OElITjBZWFIxY3lr"
    "Z09pQnpkR0YwZFhNN0NpQWdjbVYwZFhKdUlEeHpjR0Z1SUdOc1lYTnpUbUZ0WlQxN1lHSmhaR2Rs"
    "SUdKaFpHZGxMU1I3YzNSaGRIVnpmV0I5UG50c1lXSmxiSDA4TDNOd1lXNCtPd3A5IiwgInIiOiAi"
    "THk4ZzBLSFF2dEN4MFl2Umd0QzQwTFVnMFlEUXNOR0IwWUhSaTlDNzBMclF1Q0RSZ2RDNzBMN1Fz"
    "dEN3MEx6UXVDNGcwSkhSaTlDNzBMNDZJTkN5SU5DNzBMWFF2ZEdDMExVZzBZSFJndEMrMFkvUXU5"
    "QzRJTkM2MEw3UXROR0xJQ2h6Wlc1MExDQmliM1Z1WTJVc0NpOHZJSE4xY0hCeVpYTnpMQ0J5WlhC"
    "c2VWOWhkWFJ2S1N3ZzBMZ2cwTDdRdjlDMTBZRFFzTkdDMEw3UmdDRFFzdEM0MExUUXRkQzdJTUty"
    "WW05MWJtTmx3cnNzSU5DOTBMVWcwTGZRdmRDdzBZOGcwTDNRdUNEUXQ5Q3dJTkdIMFlMUXZnb3ZM"
    "eURRdnRHQzBMSFF1TkN5MExyUXNDd2cwTDNRdUNEUXV0Q3cwTHJRdnRDODBZTWcwTERRdE5HQTBM"
    "WFJnZEdETGlEUWt0QzcwTERRdE5DMTBMdlF0ZEdHSURJMUxqQTRPaURDcTlHQjBMVFF0ZEM3MExE"
    "UXVTd2cwWWZSZ3RDKzBMSFJpd292THlEUmg5QzEwTHZRdnRDeTBMWFF1dEMrMEwvUXZ0QzkwWS9S"
    "Z3RDOTBMNGcwTEhSaTlDNzBMN0N1eTRnMEozUXRkQzMwTDNRc05DNjBMN1F2TkdMMExrZzBMclF2"
    "dEMwSU5DOTBMVWcwTC9SZ05HUDBZZlF0ZEM4SU9LQWxDRFF2OUMrMExyUXNOQzMwWXZRc3RDdzBM"
    "WFF2Q0RRdXRDdzBMb2cwTFhSZ2RHQzBZdzZDaTh2SU5DeTBZdlF0TkdEMEx6UXNOQzkwTDNSaTlD"
    "NUlOQy8wTFhSZ05DMTBMTFF2dEMwSU5HRjBZUFF0dEMxSU5DdzBMM1FzOUM3MExqUXVkR0IwTHJR"
    "dnRDejBMNHVDbU52Ym5OMElFVldSVTVVWDB4QlFrVk1Vem9nVW1WamIzSmtQSE4wY21sdVp5d2dj"
    "M1J5YVc1blBpQTlJSHNLSUNCelpXNTBPaUFpMEwvUXVOR0IwWXpRdk5DK0lOQyswWUxRdjlHQTBM"
    "RFFzdEM3MExYUXZkQytJaXdLSUNCa1pXeHBkbVZ5WldRNklDTFF2OUM0MFlIUmpOQzgwTDRnMExU"
    "UXZ0R0IwWUxRc05DeTBMdlF0ZEM5MEw0aUxBb2dJRzl3Wlc0NklDTFF2OUM0MFlIUmpOQzgwTDRn"
    "MEw3Umd0QzYwWURSaTlDNzBMZ2lMQW9nSUdKdmRXNWpaVG9nSXRDKzBZTFFzZEM0MExMUXV0Q3dJ"
    "T0tBbENEUXY5QzQwWUhSak5DODBMNGcwTDNRdFNEUXROQyswWWpRdTlDK0lpd0tJQ0J5WldwbFkz"
    "UmZjM0JoYlRvZ0l0Qy8wTDdSaDlHQzBMN1FzdEM0MExvZzBMM1F0U0RRdjlHQTBMalF2ZEdQMExz"
    "ZzBML1F1TkdCMFl6UXZOQytJaXdLSUNCamIyMXdiR0ZwYm5RNklDTFF0dEN3MEx2UXZ0Q3gwTEFn"
    "MEwzUXNDRFJnZEMvMExEUXZDSXNDaUFnY21Wd2JIazZJQ0xRdnRHQzBMTFF0ZEdDSU5DNjBMdlF1"
    "TkMxMEwzUmd0Q3dJaXdLSUNCeVpYQnNlVjloZFhSdk9pQWkwTERRc3RHQzBMN1F2dEdDMExMUXRk"
    "R0NJTkM2MEx2UXVOQzEwTDNSZ3RDd0lpd0tJQ0J5WlhCc2VWOXpaVzUwT2lBaTBMelJpeURRdnRH"
    "QzBMTFF0ZEdDMExqUXU5QzRJaXdLSUNCemRYQndjbVZ6Y3pvZ0l0Q3cwTFRSZ05DMTBZRWcwTEln"
    "MFlIUmd0QyswTDh0MEx2UXVOR0IwWUxRdFNJc0NpQWdkVzV6ZFdKelkzSnBZbVU2SUNMUXZ0R0Mw"
    "TC9RdU5HQjBMclFzQ0lzQ2lBZ2MydHBjRG9nSXRDLzBMalJnZEdNMEx6UXZpRFF2OUdBMEw3UXY5"
    "R0QwWW5RdGRDOTBMNGlMQW9nSUhKbGRISjVYM05qYUdWa2RXeGxaRG9nSXRDOTBMRFF0OUM5MExE"
    "Umg5QzEwTDBnMEwvUXZ0Q3kwWUxRdnRHQUlpd0tJQ0JrYVhacGMybHZibDluWVhSbFgySnNiMk5y"
    "T2lBaTBMZlFzTkdCMEx2UXZ0QzlJTkM5MExEUXY5R0EwTERRc3RDNzBMWFF2ZEM0MFk4aUxBb2dJ"
    "RzkwYUdWeU9pQWkwTExSaGRDKzBMVFJqOUdKMExYUXRTRFFzdEM5MExVZzBML1F0ZEdBMExYUXY5"
    "QzQwWUhRdXRDNElpd0tmVHNLQ21WNGNHOXlkQ0JtZFc1amRHbHZiaUJsZG1WdWRFeGhZbVZzS0dO"
    "dlpHVTZJSE4wY21sdVp5azZJSE4wY21sdVp5QjdDaUFnY21WMGRYSnVJRVZXUlU1VVgweEJRa1ZN"
    "VTF0amIyUmxYU0I4ZkNCamIyUmxPd3A5Q2dwbGVIQnZjblFnWm5WdVkzUnBiMjRnVTNSaGRIVnpR"
    "bUZrWjJVb0NpQWdleUJ6ZEdGMGRYTXNJR3RwYm1RZ1BTQWliR1ZoWkNJZ2ZUb2dleUJ6ZEdGMGRY"
    "TTZJSE4wY21sdVp6c2dhMmx1WkQ4NklDSnNaV0ZrSWlCOElDSmpZVzF3WVdsbmJpSWdmQ0FpWlha"
    "bGJuUWlJSDBzQ2lrZ2V3b2dJR052Ym5OMElHeGhZbVZzSUQwS0lDQWdJR3RwYm1RZ1BUMDlJQ0pz"
    "WldGa0lpQS9JQ2hNUlVGRVgxTlVRVlJWVTF0emRHRjBkWE5kSUh4OElITjBZWFIxY3lrS0lDQWdJ"
    "RG9nYTJsdVpDQTlQVDBnSW1WMlpXNTBJaUEvSUdWMlpXNTBUR0ZpWld3b2MzUmhkSFZ6S1FvZ0lD"
    "QWdPaUJ6ZEdGMGRYTTdDaUFnY21WMGRYSnVJRHh6Y0dGdUlHTnNZWE56VG1GdFpUMTdZR0poWkdk"
    "bElHSmhaR2RsTFNSN2MzUmhkSFZ6ZldCOVBudHNZV0psYkgwOEwzTndZVzQrT3dwOSJ9LCB7ImZp"
    "bGUiOiAic3JjL3NjcmVlbnMvdmlld3MudHN4IiwgImEiOiAiYVcxd2IzSjBJSHNnVUdGblpYSXNJ"
    "Rk53YVc1dVpYSXNJRVZ5Y205eVFtOTRMQ0JGYlhCMGVTd2dRMkZ5WkN3Z1UzUmhkSFZ6UW1Ga1oy"
    "VXNJRkpsWVdSNVFtRmtaMlVnZlNCbWNtOXRJQ0l1TGk5amIyMXdiMjVsYm5SekwzVnBJanM9Iiwg"
    "InIiOiAiYVcxd2IzSjBJSHNnVUdGblpYSXNJRk53YVc1dVpYSXNJRVZ5Y205eVFtOTRMQ0JGYlhC"
    "MGVTd2dRMkZ5WkN3Z1UzUmhkSFZ6UW1Ga1oyVXNJRkpsWVdSNVFtRmtaMlVzSUdWMlpXNTBUR0Zp"
    "Wld3Z2ZTQm1jbTl0SUNJdUxpOWpiMjF3YjI1bGJuUnpMM1ZwSWpzPSJ9LCB7ImZpbGUiOiAic3Jj"
    "L3NjcmVlbnMvdmlld3MudHN4IiwgImEiOiAiSUNBZ0lDQWdJQ0FnSUNBZ2Uxc2lJaXdnSW5ObGJu"
    "UWlMQ0FpWkdWc2FYWmxjbVZrSWl3Z0ltSnZkVzVqWlNJc0lDSmpiMjF3YkdGcGJuUWlMQ0FpY21W"
    "d2JIa2lMQ0FpZFc1emRXSnpZM0pwWW1VaUxDQWljM1Z3Y0hKbGMzTWlYUzV0WVhBb0tIUXBJRDAr"
    "Q2lBZ0lDQWdJQ0FnSUNBZ0lDQWdQRzl3ZEdsdmJpQnJaWGs5ZTNSOUlIWmhiSFZsUFh0MGZUNTdk"
    "Q0I4ZkNBaTBMTFJnZEMxSW4wOEwyOXdkR2x2Ymo0cGZRPT0iLCAiciI6ICJJQ0FnSUNBZ0lDQWdJ"
    "Q0FnZTFzaUlpd2dJbk5sYm5RaUxDQWlZbTkxYm1ObElpd2dJbkpsYW1WamRGOXpjR0Z0SWl3Z0lu"
    "SmxjR3g1SWl3Z0luSmxjR3g1WDJGMWRHOGlMQ0FpY21Wd2JIbGZjMlZ1ZENJc0NpQWdJQ0FnSUNB"
    "Z0lDQWdJQ0FnSW5OMWNIQnlaWE56SWl3Z0luTnJhWEFpTENBaVkyOXRjR3hoYVc1MElpd2dJblZ1"
    "YzNWaWMyTnlhV0psSWwwdWJXRndLQ2gwS1NBOVBnb2dJQ0FnSUNBZ0lDQWdJQ0FnSUR4dmNIUnBi"
    "MjRnYTJWNVBYdDBmU0IyWVd4MVpUMTdkSDArZTNRZ1B5QmxkbVZ1ZEV4aFltVnNLSFFwSURvZ0l0"
    "Q3kwWUhRdFNEUmdkQyswTEhSaTlHQzBMalJqeUo5UEM5dmNIUnBiMjQrS1gwPSJ9LCB7ImZpbGUi"
    "OiAic3JjL3NjcmVlbnMvdmlld3MudHN4IiwgImEiOiAiSUNBZ0lDQWdJQ0FnSUNBZ0lDQThkR2hs"
    "WVdRK1BIUnlQangwYUQ0alBDOTBhRDQ4ZEdnKzBLTFF1TkMvUEM5MGFENDhkR2crMEpyUXNOQzgw"
    "TC9Rc05DOTBMalJqend2ZEdnK1BIUm9QdENmMFlEUXZ0Q3kwTERRdWRDMDBMWFJnRHd2ZEdnK1BI"
    "Um9QdEN2MFluUXVOQzZQQzkwYUQ0OGRHZyswSkxSZ05DMTBMelJqend2ZEdnK1BDOTBjajQ4TDNS"
    "b1pXRmtQZ29nSUNBZ0lDQWdJQ0FnSUNBZ0lEeDBZbTlrZVQ1N2NtOTNjeTV0WVhBb0tHVXBJRDAr"
    "SUNnS0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUR4MGNpQnJaWGs5ZTJVdWFXUjlQangwWkQ1N1pTNXBa"
    "SDA4TDNSa1BqeDBaRDQ4VTNSaGRIVnpRbUZrWjJVZ2MzUmhkSFZ6UFh0bExtVjJaVzUwWDNSNWNH"
    "VjlJR3RwYm1ROUltTmhiWEJoYVdkdUlpQXZQand2ZEdRK0NpQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB"
    "Z0lEeDBaRDU3WlM1allXMXdZV2xuYmw5cFpDQS9QeUFpNG9DVUluMDhMM1JrUGp4MFpENTdaUzV3"
    "Y205MmFXUmxjaUEvUHlBaTRvQ1VJbjA4TDNSa1BqeDBaRDU3WlM1dFlXbHNZbTk0WDJsa0lEOC9J"
    "Q0xpZ0pRaWZUd3ZkR1ErQ2lBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUR4MFpENTdabTEwUkdGMFpT"
    "aGxMbVYyWlc1MFgzUnpLWDA4TDNSa1Bqd3ZkSEkrQ2lBZ0lDQWdJQ0FnSUNBZ0lDQWdLU2w5UEM5"
    "MFltOWtlVDQ9IiwgInIiOiAiSUNBZ0lDQWdJQ0FnSUNBZ0lDQThkR2hsWVdRK1BIUnlQangwYUQ0"
    "alBDOTBhRDQ4ZEdnKzBLZlJndEMrSU5HQjBMdlJnOUdIMExqUXU5QyswWUhSakR3dmRHZytQSFJv"
    "UHRDZjBMN1JoOUMxMEx6Umd6d3ZkR2crUEhSb1B0Q2EwTDdRdk5HRFBDOTBhRDRLSUNBZ0lDQWdJ"
    "Q0FnSUNBZ0lDQWdJRHgwYUQ3UXI5R0owTGpRdWp3dmRHZytQSFJvUHRDUzBZRFF0ZEM4MFk4OEwz"
    "Um9Qand2ZEhJK1BDOTBhR1ZoWkQ0S0lDQWdJQ0FnSUNBZ0lDQWdJQ0E4ZEdKdlpIaytlM0p2ZDNN"
    "dWJXRndLQ2hsS1NBOVBpQW9DaUFnSUNBZ0lDQWdJQ0FnSUNBZ0lDQThkSElnYTJWNVBYdGxMbWxr"
    "ZlQ0OGRHUStlMlV1YVdSOVBDOTBaRDRLSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnUEhSa1BqeFRk"
    "R0YwZFhOQ1lXUm5aU0J6ZEdGMGRYTTllMlV1WlhabGJuUmZkSGx3WlgwZ2EybHVaRDBpWlhabGJu"
    "UWlJQzgrUEM5MFpENEtJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQSFJrUG50bExuQnZZMmhsYlhV"
    "Z2ZId2dQSE53WVc0Z1kyeGhjM05PWVcxbFBTSnRkWFJsWkNJKzRvQ1VQQzl6Y0dGdVBuMDhMM1Jr"
    "UGdvZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBOGRHUStDaUFnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJ"
    "Q0FnZTJVdWEyOXRjR0Z1YVhsaElIeDhJR1V1YTI5dGRRb2dJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lD"
    "QWdJQ0FnUHlBOFBnb2dJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lIdGxMbXR2YlhC"
    "aGJtbDVZU0EvSUR4a2FYWStlMlV1YTI5dGNHRnVhWGxoZlR3dlpHbDJQaUE2SUc1MWJHeDlDaUFn"
    "SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdlMlV1YTI5dGRTQS9JRHhrYVhZZ1kyeGhj"
    "M05PWVcxbFBTSnRkWFJsWkNJK2UyVXVhMjl0ZFgwOEwyUnBkajRnT2lCdWRXeHNmUW9nSUNBZ0lD"
    "QWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ0lDQThMejRLSUNBZ0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNB"
    "Z0lEb2dQSE53WVc0Z1kyeGhjM05PWVcxbFBTSnRkWFJsWkNJKzRvQ1VQQzl6Y0dGdVBuMEtJQ0Fn"
    "SUNBZ0lDQWdJQ0FnSUNBZ0lDQWdQQzkwWkQ0S0lDQWdJQ0FnSUNBZ0lDQWdJQ0FnSUNBZ1BIUmtQ"
    "bnRsTG0xaGFXeGliM2hmYVdRZ1B6OGdJdUtBbENKOVBDOTBaRDRLSUNBZ0lDQWdJQ0FnSUNBZ0lD"
    "QWdJQ0FnUEhSa1BudG1iWFJFWVhSbEtHVXVaWFpsYm5SZmRITXBmVHd2ZEdRK1BDOTBjajRLSUNB"
    "Z0lDQWdJQ0FnSUNBZ0lDQXBLWDA4TDNSaWIyUjVQZz09In0sIHsiZmlsZSI6ICJzcmMvYXBpL3R5"
    "cGVzLnRzIiwgImEiOiAiSUNCdFlXbHNZbTk0WDJsa09pQnpkSEpwYm1jZ2ZDQnVkV3hzT3dvZ0lH"
    "VjJaVzUwWDNSek9pQnpkSEpwYm1jZ2ZDQnVkV3hzT3dwOSIsICJyIjogIklDQnRZV2xzWW05NFgy"
    "bGtPaUJ6ZEhKcGJtY2dmQ0J1ZFd4c093b2dJR1YyWlc1MFgzUnpPaUJ6ZEhKcGJtY2dmQ0J1ZFd4"
    "c093b2dJQzh2SU5HQzBMNGcwTGJRdFNEUmdkQyswTEhSaTlHQzBMalF0U0RSZ2RDNzBMN1FzdEN3"
    "MEx6UXVDQW8wTExRdTlDdzBMVFF0ZEM3MExYUmhpQXlOUzR3T0RvZ3dxdlJnZEMwMExYUXU5Q3cw"
    "TGtzSU5HSDBZTFF2dEN4MFlzZzBZZlF0ZEM3MEw3UXN0QzEwTHJRdnRDLzBMN1F2ZEdQMFlMUXZk"
    "QytDaUFnTHk4ZzBMSFJpOUM3MEw3Q3V5a3VJTkNhMEw3UXRDRFF2dEdCMFlMUXNOQ3kwTHZRdGRD"
    "OU9pRFF2OUMrSU5DOTBMWFF2TkdESU5HQTBMRFFzZEMrMFlMUXNOQzEwWUlnMFlUUXVOQzcwWXpS"
    "Z3RHQUlOQzRJTkdCMFlMUXNOR0EwWXZRdFNEUmdkR0IwWXZRdTlDNjBMZ3VDaUFnWTJoMGJ6ODZJ"
    "SE4wY21sdVp5QjhJRzUxYkd3N0NpQWdjRzlqYUdWdGRUODZJSE4wY21sdVp5QjhJRzUxYkd3N0Np"
    "QWdhMjl0ZFQ4NklITjBjbWx1WnlCOElHNTFiR3c3Q2lBZ2EyOXRjR0Z1YVhsaFB6b2djM1J5YVc1"
    "bklId2diblZzYkRzS2ZRPT0ifV19")

груз = json.loads(base64.b64decode(ГРУЗ_B64).decode("utf-8"))
путь_модуля = os.path.join(ПАКЕТ, "sobytiya_slovami.py")

задания = []          # (полный путь, новый текст)
тексты = {}
ошибок = 0
for группа, корень in (("py", ПАКЕТ), ("web", ФРОНТ)):
    for п in груз[группа]:
        путь = os.path.join(корень, п["file"].replace("/", os.sep))
        if путь not in тексты:
            тексты[путь] = io.open(путь, encoding="utf-8").read()
        якорь = base64.b64decode(п["a"]).decode("utf-8")
        замена = base64.b64decode(п["r"]).decode("utf-8")
        уже = замена.strip().splitlines()[0] in тексты[путь]
        н = тексты[путь].count(якорь)
        метка = "уже стоит" if (н == 0 and уже) else ("%d" % н)
        print("%-26s %-52s %s" % (п["file"], якорь.strip().splitlines()[0][:52], метка))
        if н == 1:
            тексты[путь] = тексты[путь].replace(якорь, замена)
        elif not уже:
            ошибок += 1
if ошибок:
    raise SystemExit("ОТМЕНА: %d якорей не нашлось ровно по разу" % ошибок)
if not ПРИМЕНИТЬ:
    print("\nвхолостую. Применить — primenit")
    raise SystemExit(0)

метка = time.strftime("%Y%m%d-%H%M%S")
записаны = []
был_модуль = os.path.exists(путь_модуля)
try:
    io.open(путь_модуля, "w", encoding="utf-8", newline="").write(
        base64.b64decode(груз["module"]).decode("utf-8"))
    py_compile.compile(путь_модуля, doraise=True)
    print("положен модуль: sobytiya_slovami.py")
    for путь, текст in тексты.items():
        shutil.copy2(путь, путь + ".bak-" + метка)
        io.open(путь, "w", encoding="utf-8", newline="").write(текст)
        записаны.append(путь)
        if путь.endswith(".py"):
            py_compile.compile(путь, doraise=True)
        print("правлен %s" % os.path.relpath(путь, ПАКЕТ))
    # Собираем ТОЛЬКО vite, без tsc. Серверный web/src не проходит проверку
    # типов и без моих правок: в его types.ts нет MailFull, MailMsg,
    # QuotaDay, SentMessage, а в views.tsx с десяток implicit any. То есть
    # dist на сервере давно собирают не «npm run build», и требовать от
    # чужого кода чистой типизации ради подписи в ленте — не мой заход.
    # Синтаксис vite всё равно проверит и на ошибке упадёт.
    print("\nсобираю фронт (vite build, без проверки типов)...")
    в = subprocess.run(["npx.cmd", "--no-install", "vite", "build"], cwd=ФРОНТ,
                       capture_output=True, text=True, timeout=600)
    хвост = (в.stdout or "") + (в.stderr or "")
    print("\n".join(хвост.strip().splitlines()[-12:]))
    if в.returncode != 0:
        raise RuntimeError("сборка фронта вернула %d" % в.returncode)
except Exception as e:  # noqa: BLE001
    print("\nСБОЙ: %s — откатываю всё" % str(e)[:200])
    for путь in записаны:
        shutil.copy2(путь + ".bak-" + метка, путь)
    if not был_модуль and os.path.exists(путь_модуля):
        os.remove(путь_модуля)
    raise
print("\nготово. Панель подхватит после Restart-Service SenderPanel -Force")
