# setup-news-schedule.ps1 — регистрация ЕЖЕДНЕВНОГО прогона news_cron в
# планировщике Windows (задача #49-б, п.4).
#
# НЕ ИСПОЛНЯЕТСЯ СЕССИЕЙ: скрипт запускает оркестратор/владелец на сервере.
# Прогон ничего не рассылает (холд на отправку писем не задевается): он читает
# новости доноров и пишет сигналы в C:\sender\enrich.db.
#
# Предпосылки:
#   - news_cron.py / no_rss.py / freshness.py / schedule_db.py доставлены в
#     C:\sender\server\ (через дроп, канон PANEL-DEPLOY.md; рядом лежат
#     news_scan.py / enrich_db.py — news_cron импортирует их из своего каталога);
#   - секреты (PROVIDER_API_KEY, DADATA_TOKEN, DROP_TOKEN...) лежат в
#     C:\sender\server\runner-secrets.env — news_cron подхватывает их сам
#     (реюз загрузчика job_runner), в задачу планировщика их класть не нужно;
#   - питон панели: C:\Program Files\Python311\python.exe
#     (НЕ «py» без версии — это 3.12, см. PANEL-DEPLOY.md).
#
# Время: 07:00 по ЛОКАЛЬНОМУ времени сервера (сервер владельца живёт в МСК).
# Если зона сервера иная — пересчитать /ST.

$ErrorActionPreference = 'Stop'

$TaskName = 'RuspromNewsScan'
$Python   = 'C:\Program Files\Python311\python.exe'
$Script   = 'C:\sender\server\news_cron.py'
$Log      = 'C:\sender\server\news_cron.out'
$Wrapper  = 'C:\sender\server\news_cron_task.cmd'

if (-not (Test-Path $Python)) { throw "Нет питона панели: $Python" }
if (-not (Test-Path $Script)) { throw "Нет скрипта: $Script — сначала доставить через дроп" }

# Обёртка .cmd вместо длинной строки в /TR: schtasks калечит вложенные кавычки и
# перенаправление вывода, а обёртка даёт лог и -X utf8 (русская сводка не падает
# на кодировке консоли службы). rem внутри — ASCII: cmd.exe не дружит с UTF-8.
@"
@echo off
rem Generated by setup-news-schedule.ps1 - daily news_cron run (log: news_cron.out)
"$Python" -X utf8 "$Script" --days 30 >> "$Log" 2>&1
"@ | Set-Content -Path $Wrapper -Encoding ASCII

# /RU SYSTEM — прогон не зависит от логина владельца; /F — пересоздание идемпотентно
schtasks /Create /F /TN $TaskName /SC DAILY /ST 07:00 /RU SYSTEM /TR "`"$Wrapper`""

Write-Host "Задача '$TaskName' создана: ежедневно 07:00, лог $Log"
Write-Host 'Проверить:      schtasks /Query /TN RuspromNewsScan /V /FO LIST'
Write-Host 'Прогнать сейчас: schtasks /Run /TN RuspromNewsScan'
Write-Host 'Удалить:        schtasks /Delete /TN RuspromNewsScan /F'
Write-Host 'Сводка свежести: & $Python -X utf8 $Script --report'
